# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51c6d04fd33f5ad356199c7e6be169c2ba8c935373058b4cc66f7160b254f103a69a440524db293e63e5a354a1f2fd239f960393fcdc5036ec481e0372b09d64

test:
  secret_key_base: 3239b3830aa5ff49b95f0eb5b0a9b52012727f4c2bddb5616d7de23cbaba6f770659519e73e54db2e38af04b4f0b097a221d1cd392ae81781524414c31dc6d33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
